version: "3"

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ${CONTAINER_NAME}-tailscale
    hostname: mytesla
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    volumes:
      - ./data/tailscale/state:/var/lib/tailscale:rw
      - ./data/tailscale/socket:/var/run/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    labels:
      createdBy: "Apps"

  traefik:
    image: traefik:latest
    container_name: ${CONTAINER_NAME}-traefik
    network_mode: service:tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/tailscale/state:/var/lib/tailscale:rw
      - ./data/tailscale/socket:/var/run/tailscale
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.myresolver.tailscale=true
    restart: unless-stopped
    depends_on:
      - tailscale
    labels:
      createdBy: "Apps"

  teslamate:
    image: teslamate/teslamate:2.0.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    depends_on:
      - database
      - mosquitto
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=mytesla.${TS_TAILNET_NAME}
      - ENCRYPTION_KEY=${TM_ENCRYPTION_KEY}
      - TZ=${TZ}
    ports:
      - ${PANEL_APP_PORT_HTTP}:4000
    volumes:
      - ./data/teslamate:/opt/app/import
    labels:
      createdBy: "Apps"
      - "traefik.enable=true"
      - "traefik.port=4000"
      - "traefik.http.routers.teslamate.rule=Host(`mytesla.${TS_TAILNET_NAME}`)"
      - "traefik.http.routers.teslamate.entrypoints=websecure"
      - "traefik.http.routers.teslamate.tls=true"
      - "traefik.http.routers.teslamate.tls.certresolver=myresolver"
      - "traefik.http.routers.teslamate-ws.rule=Host(`mytesla.${TS_TAILNET_NAME}`) && Path(`/live/websocket`)"
      - "traefik.http.routers.teslamate-ws.entrypoints=websecure"
      - "traefik.http.routers.teslamate-ws.tls="

  grafana:
    image: teslamate/grafana:2.0.0
    container_name: ${CONTAINER_NAME}-grafana
    restart: unless-stopped
    networks:
      - 1panel-network
    depends_on:
      - database
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_DOMAIN=mytesla.${TS_TAILNET_NAME}
      - GF_SERVER_ROOT_URL=https://mytesla.${TS_TAILNET_NAME}/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    labels:
      createdBy: "Apps"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`mytesla.${TS_TAILNET_NAME}`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.port=3000"

  teslamateapi:
    image: mytesla/teslamateapi:latest
    container_name: ${CONTAINER_NAME}-teslamateapi
    restart: unless-stopped
    networks:
      - 1panel-network
    depends_on:
      - database
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - ENCRYPTION_KEY=${TM_ENCRYPTION_KEY}
      - MQTT_HOST=mosquitto
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ./data/teslamateapi:/opt/app/data
    ports:
      - ${API_PORT}:8080
    labels:
      createdBy: "Apps"
      - "traefik.enable=true"
      - "traefik.http.routers.teslamateapi.rule=Host(`mytesla.${TS_TAILNET_NAME}`) && (Path(`/api`) || PathPrefix(`/api/`))"
      - "traefik.http.routers.teslamateapi.entrypoints=websecure"
      - "traefik.http.routers.teslamateapi.tls=true"
      - "traefik.http.routers.teslamateapi.tls.certresolver=myresolver"
      - "traefik.port=8080"

  database:
    image: postgres:17
    container_name: ${CONTAINER_NAME}-database
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    labels:
      createdBy: "Apps"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ${CONTAINER_NAME}-mosquitto
    restart: unless-stopped
    networks:
      - 1panel-network
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true